# Generated by Django 3.0.3 on 2020-06-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, verbose_name='uid')),
                ('nickName', models.CharField(max_length=50, verbose_name='昵称')),
                ('wx_number', models.CharField(max_length=50, verbose_name='微信号')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'ordering': ('uid',),
            },
        ),
    ]
