# Generated by Django 3.0.3 on 2020-06-23 04:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200623_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(verbose_name='tid')),
                ('releaser_wx_number', models.CharField(max_length=50, verbose_name='发布者')),
                ('release_time', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='任务名称')),
                ('money', models.IntegerField(verbose_name='金额')),
                ('threshold_value', models.FloatField(verbose_name='阈值')),
                ('description', models.CharField(max_length=1000, verbose_name='任务描述')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(verbose_name='tid')),
                ('sentence', models.CharField(max_length=100, verbose_name='内容')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to=api.models.wrapper),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='native_place',
            field=models.CharField(default='', max_length=50, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.BooleanField(default=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('wx_number',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
