# Generated by Django 3.0.3 on 2020-06-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200623_1254'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('tid',)},
        ),
        migrations.AlterUniqueTogether(
            name='task_context',
            unique_together={('tid', 'sentence')},
        ),
    ]
