# Generated by Django 3.0.3 on 2020-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200623_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(default='请输入昵称', max_length=50, null=True, verbose_name='昵称'),
        ),
    ]
