# Generated by Django 3.0.3 on 2020-06-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='tid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='tid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='微信号'),
        ),
    ]
