# Generated by Django 3.0.3 on 2020-06-24 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200624_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_context',
            name='finish_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_context',
            name='required_times',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='task_context',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task', verbose_name='tid'),
        ),
    ]
