# Generated by Django 3.0.3 on 2020-06-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200624_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='releaser_wx_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='发布者'),
        ),
    ]
