# Generated by Django 3.0.3 on 2020-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200624_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='tid'),
        ),
    ]
