# Generated by Django 3.0.2 on 2020-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(max_length=200, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
