# Generated by Django 3.0.2 on 2020-06-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200629_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('sentence', models.CharField(max_length=100, verbose_name='内容')),
                ('required_times', models.IntegerField(default=10)),
                ('finish_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='rest',
            field=models.BigIntegerField(default=0, verbose_name='剩余语句数'),
        ),
        migrations.AddField(
            model_name='user',
            name='success_times',
            field=models.IntegerField(default=0, verbose_name='成功次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='task_times',
            field=models.IntegerField(default=0, verbose_name='做任务次数'),
        ),
        migrations.DeleteModel(
            name='Task_Context',
        ),
        migrations.AddField(
            model_name='context',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Task', verbose_name='task'),
        ),
        migrations.AlterUniqueTogether(
            name='context',
            unique_together={('task', 'sentence')},
        ),
    ]
