# Generated by Django 3.0.3 on 2020-06-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200630_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='finish_times',
        ),
        migrations.AddField(
            model_name='context',
            name='total_times',
            field=models.IntegerField(default=10),
        ),
    ]
