# Generated by Django 3.0.3 on 2020-07-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200702_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='finished_time',
            new_name='finished_times',
        ),
        migrations.AlterUniqueTogether(
            name='taskfinish',
            unique_together={('user', 'cid')},
        ),
    ]
