# Generated by Django 3.0.3 on 2020-07-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200702_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='token_baidu',
            field=models.CharField(max_length=200, verbose_name='分词'),
        ),
    ]
