# Generated by Django 3.0.3 on 2020-07-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200702_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfinish',
            old_name='cid',
            new_name='context',
        ),
        migrations.AlterUniqueTogether(
            name='taskfinish',
            unique_together={('user', 'context')},
        ),
    ]
