# Generated by Django 3.0.3 on 2020-07-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_context_threshold_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskfinish',
            unique_together=set(),
        ),
    ]
