# Generated by Django 3.0.3 on 2020-07-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200702_1156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskfinish',
            unique_together={('user', 'context')},
        ),
    ]
