# Generated by Django 3.0.3 on 2020-07-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='token',
            new_name='token_baidu',
        ),
    ]
