# Generated by Django 3.0.3 on 2020-07-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200714_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='token_baidu',
            new_name='token',
        ),
    ]
