# Generated by Django 3.0.3 on 2020-07-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200714_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='base_score',
            field=models.IntegerField(default=100, verbose_name='最高积分'),
        ),
    ]
